#ifndef HED_MCAL_ADC_INTERFACE_H_
#define HED_MCAL_ADC_INTERFACE_H_

void INIT_ADC(void);
u8 READ_ADC_SYNCH(u8 COPY_CHANNEL, u16 *COPY_DIGITAL_VAL);
u8 READ_ADC_ASYNCH(u8 COPY_CHANNEL, u16 *COPY_DIGITAL_VAL, void(*COPY_notifiFun)(void));

#endif